down and bootstrap
also, better verbose output and updated docs

diff --git a/castle b/castle
--- a/castle
+++ b/castle
@@ -4,8 +4,10 @@
 # shellcheck disable=SC3030
 # shellcheck disable=SC1078                                                  #
 DIR=$(dirname "$(readlink -f -- "$0")")
-C_GREEN="\033[0;32m"
-C_BLUE="\033[0;34m"
+C_ERROR="\033[0;31m"
+C_WARN="\033[0;33m"
+C_NOTICE="\033[0;32m"
+C_VERBOSE="\033[0;34m"
 C_NONE="\033[0m"
 set_usage() {
   USAGE="""Usage: ${CMD:=${0##*/}} ${1:-"[bootstrap|up|down|build|help]"} [APPS...|(-a|--all)] [(-v|--verbose)] [(-d|--dry-run)] [(-h|--help)]
@@ -14,7 +16,7 @@ set_usage() {
     
   Options:
     -a|--all - apply to all apps
-    -v|--verbose - output additional info to stderr
+    -v|--verbose - output additional info to stderr; pass multiple times for greater verbosity
     -d|--dry-run - preview the commends to be run, but do not execute them
     -h|--help - display this help text
     ${2}"""
@@ -31,13 +33,21 @@ exit_runtime () {
   printf >&2 "Sandcastles require a container runtime\nYou must install either podman (and podman-compose) or docker"; 
   exit 3;
 }
+exit_err() {
+  printf >&2 "${C_ERROR}%s Error!${C_NONE}\n%b\n" "$1" "⤷ $2"; exit 4
+}
 exit_usage() { printf "%s\n" "$USAGE"; exit 0; }
 exit_help() { printf "%s\n%s\n" "$HELP" "$USAGE"; exit 0; }
 check () { { [ "$1" != "$EOL" ] && [ "$1" != '--' ]; } || exit2 "missing argument" "$2"; }  # avoid infinite loop
 verbose () {
-  if [ "$opt_verbose" = "true" ]; then
+  if [ "$opt_verbose" -gt 0 ]; then
     debug=$1; shift
-    printf "${C_GREEN}%s${C_NONE}\n%s\n" "$debug"  "⤷ $(printf "%s " "$@")" >&2
+    printf "${C_NOTICE}%s${C_NONE}\n%s\n" "$debug"  "⤷ $(printf "%s " "$@")" >&2
+  fi
+}
+verbose2 () {
+  if [ $opt_verbose -gt 1 ]; then
+    verbose "$@"
   fi
 }
 
@@ -46,10 +56,10 @@ run() {
   debug=$1; shift
   cmd_args=("$@")
   if [ "$opt_dryrun" = "true" ]; then
-    printf "${C_BLUE}dry-run${C_NONE}\n%s\n" "⤷ $(printf "%s %s" "${cmd_args[*]}" "${arg_pass[*]}")" >&2
+    printf "${C_VERBOSE}dry-run${C_NONE}\n%s\n" "⤷ $(printf "%s %s" "${cmd_args[*]}" "${arg_pass[*]}")" >&2
     return
   fi
-  if [ "$opt_verbose" = "true" ]; then
+  if [ "$opt_verbose" -gt 0 ]; then
     verbose "$debug" "${cmd_args[*]}"
   fi
   if [ ${#arg_pass[@]} -gt 0 ]; then
@@ -92,6 +102,7 @@ esac
 # parse remaining command-line options
 set -- "$@" "${EOL:=$(printf '\1\3\3\7')}"  # end-of-list marker
 opt_apps=()
+opt_verbose=0
 arg_pass=()
 while [ "$1" != "$EOL" ]; do
   opt="$1"; shift
@@ -101,7 +112,7 @@ while [ "$1" != "$EOL" ]; do
     -a | --all      ) opt_all=true;;
     -h | --help     ) exit_help;;
     -r | --required ) opt_required=true;;
-    -v | --verbose  ) opt_verbose=true;;
+    -v | --verbose  ) opt_verbose=$((opt_verbose + 1));;
     -d | --dry-run  ) opt_dryrun=true;;
 
     # process special cases
@@ -121,7 +132,7 @@ else
   exit_runtime
 fi
 
-verbose "parsed options" """DIR = '$DIR'
+verbose2 "parsed options" """DIR = '$DIR'
   action = '$opt_action'
   arg_pass = ${arg_pass[*]}
   apps = ${opt_apps[*]}
@@ -142,7 +153,7 @@ case $opt_action in
       for n in ${opt_apps[*]}; do compose_files+=("-f" "$n.compose.yml"); done
     fi
     cmd_args=("$env_runtime" "compose" "${compose_files[@]}" "up" "-d")
-    run "$opt_action" "${cmd_args[@]}"
+    run "compose up" "${cmd_args[@]}"
   ;;
 
   build )
@@ -177,8 +188,47 @@ case $opt_action in
       if [ $env_runtime = "podman" ]; then
         cmd_args+=("--format" "docker")
       fi
-      run "$opt_action" "${cmd_args[@]}"
+      run "build images" "${cmd_args[@]}"
       i=$((i+2))
     done
+  ;;
+
+  down )
+    compose_files=()
+    if [ "$opt_all" = "true" ]; then
+      compose_files+=("-f" "$DIR/docker-compose.yml")
+      all_files=$(find "$DIR" -type f -name "*.compose.yml")
+      for n in ${all_files[*]}; do compose_files+=("-f" "$n"); done 
+    else
+      for n in ${opt_apps[*]}; do compose_files+=("-f" "$n.compose.yml"); done
+    fi
+    cmd_args=("$env_runtime" "compose" "${compose_files[@]}" "down")
+    run "compose down" "${cmd_args[@]}"
+  ;;
+
+  bootstrap )
+    if [ -d "$DIR/volumes/root-ca/secrets" ]; then
+        exit_err "$opt_action" """Refusing to overwrite data in ${C_WARN}$DIR/volumes/root-ca/${C_NONE}
+  This project has already been bootstrapped. You must remove the secrets stored in
+  ${C_WARN}$DIR/volumes/root-ca/${C_NONE} before you can bootstrap again.
+  Those secrets cannot be recovered later! Make a copy of them, or revoke trust in them before they are deleted."""
+    fi
+
+    run "create sandcastles internal CA" "$env_runtime" "compose" "-f" "$DIR/bootstrap.yml" "up" "-d"
+    container_id=$(run "get container id" "$env_runtime" "compose" "-f" "bootstrap.yml" "ps" "-q")
+    container_id=${container_id:-"dry-run_container"}
+    run "wait for container" sleep 1
+    run "extract private key for sandcastles internal CA" "$env_runtime" "cp" "$container_id:/home/step/templates" "$DIR/volumes/root-ca/"
+    run "..." "$env_runtime" "cp" "$container_id:/home/step/secrets" "$DIR/volumes/root-ca/"
+    run "..." "$env_runtime" "cp" "$container_id:/home/step/db" "$DIR/volumes/root-ca/"
+    run "..." "$env_runtime" "cp" "$container_id:/home/step/certs" "$DIR/volumes/root-ca/"
+    run "..." "$env_runtime" "compose" "-f" "bootstrap.yml" "down"
+    
+    run "configure access to sandcastles internal CA" mkdir "-p" "$DIR/volumes/root-ca/config"
+    run "..." "cp" "$DIR/volumes/ca.json" "$DIR/volumes/root-ca/config/ca.json" "-f"
+    run "..." "find" "$DIR/volumes/root-ca" "-type" "d" "-exec" "chmod" "755" "{}" "+"
+    run "..." "find" "$DIR/volumes/root-ca" "-type" "f" "-exec" "chmod" "644" "{}" "+"
+    
+    run "collect info about the runtime environment" printf "%s\n" "DOCKER_PATH=${DOCKER_HOST//"unix://"}" > "$DIR/.env"
   ;;
 esac
